name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Create GitHub Pages branch
        run: |
          git checkout -b gh-pages
          git push -u origin gh-pages
        if: "!contains(github.ref, 'refs/heads/gh-pages')"
      - name: Deploy to GitHub Pages
        uses: actions/deploy@v1
        with:
          repository_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: dist
